# Generated by Django 3.1.4 on 2020-12-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_article_published_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_field', models.CharField(max_length=70)),
                ('option', models.CharField(choices=[('A', 'blue'), ('B', 'green'), ('C', 'white')], max_length=1)),
            ],
        ),
    ]
